export type AlmanacCrop = {
  id: string;
  emoji: string;
  bg: string;
  name: string;
  cat: string;
  catLabel: string;
  sci: string;
  price: string;
  priceNum: number;
  harvest: string;
  harvestDays: number;
  planted: string;
  yield: string;
  water: string;
  waterNum: number;
  difficulty: 'Easy' | 'Moderate' | 'Hard';
  ph: string;
  spacing: string;
  companions: string[];
  avoid: string[];
  //        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec
  season: [
    boolean, boolean, boolean, boolean, boolean, boolean,
    boolean, boolean, boolean, boolean, boolean, boolean,
  ];
  tips: string[];
};

export const ALMANAC_CROPS: AlmanacCrop[] = [
  {
    id: crypto.randomUUID(),
    emoji: '🥬',
    bg: '#f0fdf4',
    name: 'Pechay',
    cat: 'leafy',
    catLabel: 'Leafy Green',
    sci: 'Brassica rapa subsp. chinensis',
    price: '₱40–55 / kg',
    priceNum: 47,
    harvest: '30–45 days',
    harvestDays: 37,
    planted: 'Oct – Feb',
    yield: '~2.5 kg / sqm',
    water: 'Moderate',
    waterNum: 2,
    difficulty: 'Easy',
    ph: '6.0–7.0',
    spacing: '15 cm',
    companions: ['Kamatis', 'Sibuyas', 'Luya'],
    avoid: ['Bawang'],
    season: [false, false, true, true, true, true, false, false, false, true, true, true],
    tips: [
      'Grows best in cool weather — ideal for highland areas like Benguet and Bukidnon.',
      'Susceptible to aphids; neem oil spray works as an organic deterrent.',
      'Harvest outer leaves first to extend the productive life of the plant.',
      'Prefers well-draining, slightly alkaline soil enriched with compost.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🍅',
    bg: '#fff7ed',
    name: 'Kamatis',
    cat: 'fruit_veg',
    catLabel: 'Fruit Veg',
    sci: 'Solanum lycopersicum',
    price: '₱50–80 / kg',
    priceNum: 65,
    harvest: '60–80 days',
    harvestDays: 70,
    planted: 'Nov – Jan',
    yield: '~4 kg / sqm',
    water: 'Regular',
    waterNum: 2,
    difficulty: 'Moderate',
    ph: '6.0–6.8',
    spacing: '45 cm',
    companions: ['Pechay', 'Pipino', 'Bell Pepper'],
    avoid: ['Talong'],
    season: [false, false, true, true, true, false, false, false, false, false, true, true],
    tips: [
      'Stake plants early — kamatis topples easily once fruiting starts.',
      'Pinch off suckers to focus energy on fewer, larger fruits.',
      'Water at the base only; wet foliage encourages blight.',
      'Add calcium to the soil to prevent blossom end rot.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥦',
    bg: '#f0fdf4',
    name: 'Broccoli',
    cat: 'brassica',
    catLabel: 'Brassica',
    sci: 'Brassica oleracea var. italica',
    price: '₱80–110 / kg',
    priceNum: 95,
    harvest: '60–90 days',
    harvestDays: 75,
    planted: 'Sep – Dec',
    yield: '~1.5 kg / sqm',
    water: 'Moderate',
    waterNum: 2,
    difficulty: 'Hard',
    ph: '6.0–7.0',
    spacing: '50 cm',
    companions: ['Sibuyas', 'Luya'],
    avoid: ['Kamatis', 'Talong'],
    season: [false, false, true, true, false, false, false, false, false, true, true, true],
    tips: [
      'Needs cool temperatures — plant in the highlands or during the dry season.',
      'Harvest the central head before flowers open for best flavor.',
      'Side shoots keep producing for weeks after the main head is cut.',
      'Row covers protect against caterpillars and imported cabbageworm.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🧅',
    bg: '#fdf4ff',
    name: 'Sibuyas',
    cat: 'allium',
    catLabel: 'Allium',
    sci: 'Allium cepa',
    price: '₱50–70 / kg',
    priceNum: 60,
    harvest: '90–120 days',
    harvestDays: 105,
    planted: 'Oct – Dec',
    yield: '~2 kg / sqm',
    water: 'Low',
    waterNum: 1,
    difficulty: 'Moderate',
    ph: '6.0–7.0',
    spacing: '10 cm',
    companions: ['Kamatis', 'Karot'],
    avoid: ['Bawang'],
    season: [false, false, true, true, true, false, false, false, false, false, false, true],
    tips: [
      'Reduce watering 2 weeks before harvest to improve bulb firmness.',
      'Plant in raised beds to prevent waterlogging and rot.',
      'Tops falling over naturally signals they are ready to harvest.',
      'Store cured bulbs in a cool, ventilated spot for up to 6 months.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥕',
    bg: '#fff7ed',
    name: 'Karot',
    cat: 'root',
    catLabel: 'Root Crop',
    sci: 'Daucus carota subsp. sativus',
    price: '₱30–50 / kg',
    priceNum: 40,
    harvest: '70–80 days',
    harvestDays: 75,
    planted: 'Oct – Jan',
    yield: '~3 kg / sqm',
    water: 'Moderate',
    waterNum: 2,
    difficulty: 'Easy',
    ph: '6.0–6.8',
    spacing: '5 cm',
    companions: ['Sibuyas', 'Luya'],
    avoid: [],
    season: [false, false, true, true, true, false, false, false, false, true, true, true],
    tips: [
      'Loosen soil to at least 30 cm depth — compact soil causes forked roots.',
      'Thin seedlings to 5 cm spacing for proper bulb development.',
      'Carrots taste noticeably sweeter after a cold spell.',
      'Avoid fresh manure; it causes roots to fork and splits development.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🍆',
    bg: '#fdf4ff',
    name: 'Talong',
    cat: 'fruit_veg',
    catLabel: 'Fruit Veg',
    sci: 'Solanum melongena',
    price: '₱25–40 / kg',
    priceNum: 32,
    harvest: '65–80 days',
    harvestDays: 72,
    planted: 'Year-round',
    yield: '~3.5 kg / sqm',
    water: 'Regular',
    waterNum: 2,
    difficulty: 'Easy',
    ph: '5.5–6.8',
    spacing: '60 cm',
    companions: ['Pechay', 'Pipino'],
    avoid: ['Kamatis'],
    season: [true, true, true, true, true, true, true, true, true, true, true, true],
    tips: [
      'One of the easiest vegetables to grow in Philippine conditions.',
      'Harvest when skin is shiny — dull skin means it is overripe.',
      'Cut with a bit of stem attached to extend shelf life after harvest.',
      'Rotate with non-solanaceous crops every 2 years to prevent disease buildup.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🧄',
    bg: '#fafaf9',
    name: 'Bawang',
    cat: 'allium',
    catLabel: 'Allium',
    sci: 'Allium sativum',
    price: '₱60–90 / 100g',
    priceNum: 75,
    harvest: '120–150 days',
    harvestDays: 135,
    planted: 'Oct – Nov',
    yield: '~1 kg / sqm',
    water: 'Low',
    waterNum: 1,
    difficulty: 'Moderate',
    ph: '6.0–7.0',
    spacing: '10 cm',
    companions: ['Karot', 'Kamatis'],
    avoid: ['Sibuyas', 'Pechay'],
    season: [false, false, false, true, true, false, false, false, false, false, true, true],
    tips: [
      'Plant individual cloves pointy-side up, 5 cm deep.',
      'Stop watering entirely 3 weeks before harvest to cure the bulbs.',
      'Braid dried tops together and hang in a cool dry place for storage.',
      'Mulch around plants to suppress weeds and retain soil moisture.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🫑',
    bg: '#f0fdf4',
    name: 'Bell Pepper',
    cat: 'pepper',
    catLabel: 'Pepper',
    sci: 'Capsicum annuum',
    price: '₱70–100 / kg',
    priceNum: 85,
    harvest: '70–90 days',
    harvestDays: 80,
    planted: 'Oct – Jan',
    yield: '~2 kg / sqm',
    water: 'Regular',
    waterNum: 2,
    difficulty: 'Moderate',
    ph: '6.0–6.8',
    spacing: '40 cm',
    companions: ['Kamatis', 'Pechay'],
    avoid: ['Talong'],
    season: [false, false, true, true, true, false, false, false, false, false, true, true],
    tips: [
      'Start seeds indoors 6–8 weeks before transplanting outdoors.',
      'Consistent watering prevents blossom end rot.',
      'Green peppers are unripe — leave them longer for red or yellow.',
      'Use a balanced fertilizer when flowers begin to appear.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥒',
    bg: '#f0fdf4',
    name: 'Pipino',
    cat: 'fruit_veg',
    catLabel: 'Fruit Veg',
    sci: 'Cucumis sativus',
    price: '₱20–35 / kg',
    priceNum: 27,
    harvest: '50–60 days',
    harvestDays: 55,
    planted: 'Year-round',
    yield: '~4 kg / sqm',
    water: 'High',
    waterNum: 3,
    difficulty: 'Easy',
    ph: '6.0–7.0',
    spacing: '30 cm',
    companions: ['Kangkong', 'Pechay'],
    avoid: [],
    season: [true, true, true, true, true, false, false, false, true, true, true, true],
    tips: [
      'Provide a trellis — vertical growth improves air circulation and yield.',
      'Harvest frequently; leaving overripe fruit on the vine slows new growth.',
      'Bitter taste usually means inconsistent watering — keep moisture steady.',
      'Mulch soil to prevent splash-back and reduce fungal disease.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🌶️',
    bg: '#fff7ed',
    name: 'Siling Labuyo',
    cat: 'pepper',
    catLabel: 'Pepper',
    sci: 'Capsicum frutescens',
    price: '₱80–150 / 100g',
    priceNum: 115,
    harvest: '70–90 days',
    harvestDays: 80,
    planted: 'Year-round',
    yield: '~1.5 kg / sqm',
    water: 'Low',
    waterNum: 1,
    difficulty: 'Easy',
    ph: '5.5–7.0',
    spacing: '40 cm',
    companions: ['Kamatis', 'Pechay'],
    avoid: [],
    season: [true, true, true, true, true, true, true, true, true, true, true, true],
    tips: [
      'One of the most heat-tolerant crops — thrives even in dry conditions.',
      'The plant is perennial and can produce for 2–3 years if maintained.',
      'Wear gloves when harvesting to avoid skin irritation.',
      'Prune lightly after each harvest flush to encourage new growth.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🌿',
    bg: '#f0fdf4',
    name: 'Luya',
    cat: 'herb',
    catLabel: 'Herb',
    sci: 'Zingiber officinale',
    price: '₱40–70 / 100g',
    priceNum: 55,
    harvest: '8–10 months',
    harvestDays: 270,
    planted: 'Mar – May',
    yield: '~2 kg / sqm',
    water: 'Moderate',
    waterNum: 2,
    difficulty: 'Moderate',
    ph: '5.5–6.5',
    spacing: '20 cm',
    companions: ['Pechay', 'Karot'],
    avoid: [],
    season: [false, false, false, false, false, false, false, false, false, true, true, true],
    tips: [
      'Plant rhizomes with visible buds just below the soil surface.',
      'Prefers partial shade — avoid direct afternoon sun.',
      'Young ginger can be harvested at 5 months; mature at 8–10 months.',
      'Good drainage is critical — waterlogged soil causes rhizome rot.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥬',
    bg: '#f0fdf4',
    name: 'Kangkong',
    cat: 'leafy',
    catLabel: 'Leafy Green',
    sci: 'Ipomoea aquatica',
    price: '₱15–25 / bundle',
    priceNum: 20,
    harvest: '20–30 days',
    harvestDays: 25,
    planted: 'Year-round',
    yield: '~3 kg / sqm',
    water: 'High',
    waterNum: 3,
    difficulty: 'Easy',
    ph: '5.5–7.0',
    spacing: '20 cm',
    companions: ['Talong', 'Pipino'],
    avoid: [],
    season: [true, true, true, true, true, true, true, true, true, true, true, true],
    tips: [
      'One of the fastest-growing leafy vegetables — ready in under a month.',
      'Can be grown in water or moist soil equally well.',
      'Cut 5 cm above the soil to encourage regrowth for multiple harvests.',
      'In rainy months, ensure excess water can drain to prevent root rot.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🌱',
    bg: '#f0fdf4',
    name: 'Ampalaya',
    cat: 'fruit_veg',
    catLabel: 'Fruit Veg',
    sci: 'Momordica charantia',
    price: '₱40–60 / kg',
    priceNum: 50,
    harvest: '55–65 days',
    harvestDays: 60,
    planted: 'Feb – May',
    yield: '~2.5 kg / sqm',
    water: 'Moderate',
    waterNum: 2,
    difficulty: 'Easy',
    ph: '6.0–6.7',
    spacing: '50 cm',
    companions: ['Kangkong', 'Pipino'],
    avoid: [],
    season: [false, false, false, true, true, true, true, false, false, false, false, false],
    tips: [
      'Provide a strong trellis — vines grow vigorously and need support.',
      "Harvest when fruits are dark green and slightly soft; don't wait too long.",
      'Rich in iron and Vitamin C — one of the most nutritious local crops.',
      'Soak seeds in water for 24 hours before planting to improve germination.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🌾',
    bg: '#fffbeb',
    name: 'Sitaw',
    cat: 'fruit_veg',
    catLabel: 'Fruit Veg',
    sci: 'Vigna unguiculata subsp. sesquipedalis',
    price: '₱25–45 / kg',
    priceNum: 35,
    harvest: '45–60 days',
    harvestDays: 52,
    planted: 'Mar – Sep',
    yield: '~3 kg / sqm',
    water: 'Low',
    waterNum: 1,
    difficulty: 'Easy',
    ph: '5.5–6.5',
    spacing: '25 cm',
    companions: ['Kangkong', 'Pechay'],
    avoid: [],
    season: [false, false, true, true, true, true, true, true, true, false, false, false],
    tips: [
      'One of the most productive crops for small-scale Filipino farmers.',
      'Harvest beans when pods are long but seeds not yet bulging.',
      'Excellent nitrogen-fixer — improves soil for the next crop rotation.',
      'Does not need much fertilizer; too much nitrogen reduces pod formation.',
    ],
  },
];