export type AlmanacCrop = {
  id: string;
  emoji: string;
  bg: string;
  name: string;
  cat: string;
  catLabel: string;
  sci: string;
  price: string;
  harvest: string;
  planted: string;
  yield: string;
  water: string;
  //        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec
  season: [
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
  ];
  tips: string[];
};

export const ALMANAC_CROPS: AlmanacCrop[] = [
  {
    id: crypto.randomUUID(),
    emoji: '🥬',
    bg: '#f0fdf4',
    name: 'Pechay',
    cat: 'leafy',
    catLabel: 'Leafy green',
    sci: 'Brassica rapa subsp. chinensis',
    price: '₱40–55 / kg',
    harvest: '30–45 days',
    planted: 'Oct – Feb',
    yield: '~2.5 kg / sqm',
    water: 'Moderate',
    season: [
      false,
      false,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
    ],
    tips: [
      'Grows best in cool weather — ideal for highland areas like Benguet and Bukidnon.',
      'Susceptible to aphids; neem oil spray works as an organic deterrent.',
      'Harvest outer leaves first to extend the productive life of the plant.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🍅',
    bg: '#fff7ed',
    name: 'Kamatis',
    cat: 'fruit_veg',
    catLabel: 'Fruit veg',
    sci: 'Solanum lycopersicum',
    price: '₱50–80 / kg',
    harvest: '60–80 days',
    planted: 'Nov – Jan',
    yield: '~4 kg / sqm',
    water: 'Regular',
    season: [
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
    ],
    tips: [
      'Stake plants early — kamatis topples easily once fruiting starts.',
      'Pinch off suckers to focus energy on fewer, larger fruits.',
      'Water at the base only; wet foliage encourages blight.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥦',
    bg: '#f0fdf4',
    name: 'Broccoli',
    cat: 'brassica',
    catLabel: 'Brassica',
    sci: 'Brassica oleracea var. italica',
    price: '₱80–110 / kg',
    harvest: '60–90 days',
    planted: 'Sep – Dec',
    yield: '~1.5 kg / sqm',
    water: 'Moderate',
    season: [
      false,
      false,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
    ],
    tips: [
      'Needs cool temperatures — plant in the highlands or during the dry season.',
      'Harvest the central head before flowers open for best flavor.',
      'Side shoots keep producing for weeks after the main head is cut.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🧅',
    bg: '#fdf4ff',
    name: 'Sibuyas',
    cat: 'allium',
    catLabel: 'Allium',
    sci: 'Allium cepa',
    price: '₱50–70 / kg',
    harvest: '90–120 days',
    planted: 'Oct – Dec',
    yield: '~2 kg / sqm',
    water: 'Low',
    season: [
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
    ],
    tips: [
      'Reduce watering 2 weeks before harvest to improve bulb firmness.',
      'Plant in raised beds to prevent waterlogging and rot.',
      'Tops falling over naturally signals they are ready to harvest.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥕',
    bg: '#fff7ed',
    name: 'Karot',
    cat: 'root',
    catLabel: 'Root crop',
    sci: 'Daucus carota subsp. sativus',
    price: '₱30–50 / kg',
    harvest: '70–80 days',
    planted: 'Oct – Jan',
    yield: '~3 kg / sqm',
    water: 'Moderate',
    season: [
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
    ],
    tips: [
      'Loosen soil to at least 30cm depth — compact soil causes forked roots.',
      'Thin seedlings to 5cm spacing for proper bulb development.',
      'Carrots taste noticeably sweeter after a cold spell.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🍆',
    bg: '#fdf4ff',
    name: 'Talong',
    cat: 'fruit_veg',
    catLabel: 'Fruit veg',
    sci: 'Solanum melongena',
    price: '₱25–40 / kg',
    harvest: '65–80 days',
    planted: 'Year-round',
    yield: '~3.5 kg / sqm',
    water: 'Regular',
    season: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    tips: [
      'One of the easiest vegetables to grow in Philippine conditions.',
      'Harvest when skin is shiny — dull skin means it is overripe.',
      'Cut with a bit of stem attached to extend shelf life after harvest.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🧄',
    bg: '#fafaf9',
    name: 'Bawang',
    cat: 'allium',
    catLabel: 'Allium',
    sci: 'Allium sativum',
    price: '₱60–90 / 100g',
    harvest: '120–150 days',
    planted: 'Oct – Nov',
    yield: '~1 kg / sqm',
    water: 'Low',
    season: [
      false,
      false,
      false,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
    ],
    tips: [
      'Plant individual cloves pointy-side up, 5cm deep.',
      'Stop watering entirely 3 weeks before harvest to cure the bulbs.',
      'Braid dried tops together and hang in a cool dry place for storage.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🫑',
    bg: '#f0fdf4',
    name: 'Bell Pepper',
    cat: 'pepper',
    catLabel: 'Pepper',
    sci: 'Capsicum annuum',
    price: '₱70–100 / kg',
    harvest: '70–90 days',
    planted: 'Oct – Jan',
    yield: '~2 kg / sqm',
    water: 'Regular',
    season: [
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
    ],
    tips: [
      'Start seeds indoors 6–8 weeks before transplanting outdoors.',
      'Consistent watering prevents blossom end rot.',
      'Green peppers are unripe — leave them longer for red or yellow.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥒',
    bg: '#f0fdf4',
    name: 'Pipino',
    cat: 'fruit_veg',
    catLabel: 'Fruit veg',
    sci: 'Cucumis sativus',
    price: '₱20–35 / kg',
    harvest: '50–60 days',
    planted: 'Year-round',
    yield: '~4 kg / sqm',
    water: 'High',
    season: [
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
    ],
    tips: [
      'Provide a trellis — vertical growth improves air circulation and yield.',
      'Harvest frequently; leaving overripe fruit on the vine slows new growth.',
      'Bitter taste usually means inconsistent watering — keep moisture steady.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🌶️',
    bg: '#fff7ed',
    name: 'Siling Labuyo',
    cat: 'pepper',
    catLabel: 'Pepper',
    sci: 'Capsicum frutescens',
    price: '₱80–150 / 100g',
    harvest: '70–90 days',
    planted: 'Year-round',
    yield: '~1.5 kg / sqm',
    water: 'Low',
    season: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    tips: [
      'One of the most heat-tolerant crops — thrives even in dry conditions.',
      'The plant is perennial and can produce for 2–3 years if maintained.',
      'Wear gloves when harvesting to avoid skin irritation.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🌿',
    bg: '#f0fdf4',
    name: 'Luya',
    cat: 'herb',
    catLabel: 'Herb',
    sci: 'Zingiber officinale',
    price: '₱40–70 / 100g',
    harvest: '8–10 months',
    planted: 'Mar – May',
    yield: '~2 kg / sqm',
    water: 'Moderate',
    season: [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
    ],
    tips: [
      'Plant rhizomes with visible buds just below the soil surface.',
      'Prefers partial shade — avoid direct afternoon sun.',
      'Young ginger can be harvested at 5 months; mature at 8–10 months.',
    ],
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥬',
    bg: '#f0fdf4',
    name: 'Kangkong',
    cat: 'leafy',
    catLabel: 'Leafy green',
    sci: 'Ipomoea aquatica',
    price: '₱15–25 / bundle',
    harvest: '20–30 days',
    planted: 'Year-round',
    yield: '~3 kg / sqm',
    water: 'High',
    season: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
    tips: [
      'One of the fastest-growing leafy vegetables — ready in under a month.',
      'Can be grown in water or moist soil equally well.',
      'Cut 5cm above the soil to encourage regrowth for multiple harvests.',
    ],
  },
];
