// ─── Garden notification types ─────────────────────────────────────────────
// A lightweight, local (per-browser) notification feed for the Garden page's
// bell. Entries are generated by watching existing garden state for
// transitions (a plot becoming harvest-ready, a pest appearing, etc.) — this
// file never reads from or writes to game state itself, it only describes
// what a notification looks like.

export type GardenNotificationType =
  | 'crop_ready'
  | 'needs_water'
  | 'pest_attack'
  | 'weather_changed'
  | 'quest_completed'
  | 'level_up';

// Where clicking a notification should take the player.
export type NotificationLink =
  | { kind: 'plot'; plotIndex: number }
  | { kind: 'quests' }
  | { kind: 'route'; path: string }
  | { kind: 'none' };

export type GardenNotification = {
  id: string;
  type: GardenNotificationType;
  icon: string;
  title: string;
  message: string;
  createdAt: number; // ms epoch
  read: boolean;
  link: NotificationLink;
};

// Snapshot of the garden-relevant state we diff against to detect new
// events. Deliberately minimal — just enough to notice a transition.
export type GardenSnapshot = {
  plots: { status: string; hp: number; cropId: string | null }[];
  pestKeys: string[]; // `${plotIdx}:${expiresAt}` — stable per pest occurrence
  weatherLabel: string;
  questProgress: Record<string, number>;
  level: number;
};
