// ── emoji icon reference ──────────────────────────────────────────────────────
// Plain Unicode emoji, no icon library needed.
//   🥬 pechay / leafy greens    🌽 corn        🍅 tomato      🥦 broccoli
//   🧅 onion                    🥕 carrot       🫑 bell pepper  🍆 eggplant
//   🥒 cucumber                 🧄 garlic       🌶️ chili        🥔 potato
// ─────────────────────────────────────────────────────────────────────────────

export const DUMMY_CROPS = [
  {
    id: crypto.randomUUID(),
    emoji: '🥬',
    bg: '#f0fdf4',
    name: 'Pechay',
    meta: 'Fresh harvest · 5kg',
    price: 45,
    unit: 'kg',
    seller: 'Rosa L.',
    initials: 'RL',
    avatarBg: '#dcfce7',
    avatarColor: '#166534',
    km: 1.2,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🌽',
    bg: '#fef9c3',
    name: 'Sweet Corn',
    meta: 'Bicolano · 20pcs',
    price: 12,
    unit: 'pc',
    seller: 'Mang Roel',
    initials: 'MR',
    avatarBg: '#fef9c3',
    avatarColor: '#854d0e',
    km: 2.0,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🍅',
    bg: '#fff7ed',
    name: 'Kamatis',
    meta: 'Cherry type · 3kg',
    price: 60,
    unit: 'kg',
    seller: 'Lola Cita',
    initials: 'LC',
    avatarBg: '#fee2e2',
    avatarColor: '#991b1b',
    km: 0.8,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥦',
    bg: '#f0fdf4',
    name: 'Broccoli',
    meta: 'Benguet · 2kg',
    price: 90,
    unit: 'kg',
    seller: 'Jun B.',
    initials: 'JB',
    avatarBg: '#dcfce7',
    avatarColor: '#166534',
    km: 3.1,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🧅',
    bg: '#fdf4ff',
    name: 'Sibuyas',
    meta: 'Red · 10kg bag',
    price: 55,
    unit: 'kg',
    seller: 'Ate Luz',
    initials: 'AL',
    avatarBg: '#fae8ff',
    avatarColor: '#7e22ce',
    km: 1.7,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥕',
    bg: '#fff7ed',
    name: 'Karot',
    meta: 'Sliced ready · 1kg',
    price: 35,
    unit: 'kg',
    seller: 'Pedro D.',
    initials: 'PD',
    avatarBg: '#ffedd5',
    avatarColor: '#9a3412',
    km: 4.0,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🫑',
    bg: '#f0fdf4',
    name: 'Bell Pepper',
    meta: 'Mixed colors · 1kg',
    price: 80,
    unit: 'kg',
    seller: 'Maria S.',
    initials: 'MS',
    avatarBg: '#dcfce7',
    avatarColor: '#166534',
    km: 2.3,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🍆',
    bg: '#fdf4ff',
    name: 'Talong',
    meta: 'Long variety · 4kg',
    price: 30,
    unit: 'kg',
    seller: 'Kuya Ben',
    initials: 'KB',
    avatarBg: '#f3e8ff',
    avatarColor: '#6b21a8',
    km: 1.1,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🥒',
    bg: '#f0fdf4',
    name: 'Pipino',
    meta: 'Crisp · 2kg',
    price: 25,
    unit: 'kg',
    seller: 'Aling Nena',
    initials: 'AN',
    avatarBg: '#dcfce7',
    avatarColor: '#166534',
    km: 0.5,
  },
  {
    id: crypto.randomUUID(),
    emoji: '🧄',
    bg: '#fafaf9',
    name: 'Bawang',
    meta: 'Native · 500g',
    price: 70,
    unit: '100g',
    seller: 'Tatay Erwin',
    initials: 'TE',
    avatarBg: '#f5f5f4',
    avatarColor: '#57534e',
    km: 3.8,
  },
];


